export const CATEGORY_EMOJI_REQUIRED = "CATEGORY_EMOJI_REQUIRED";
export const CATEGORY_NAME_DUPLICATE = "CATEGORY_NAME_DUPLICATE";
export const CATEGORY_NAME_REQUIRED = "CATEGORY_NAME_REQUIRED";
export const CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";

export type CategoryErrorCode =
  | typeof CATEGORY_EMOJI_REQUIRED
  | typeof CATEGORY_NAME_DUPLICATE
  | typeof CATEGORY_NAME_REQUIRED
  | typeof CATEGORY_NOT_FOUND;
